name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build WebApp Image
      run: docker build -t ghcr.io/aslisarikaya/note-app-docker-webapp:latest ./WebApp

    - name: Push WebApp Image
      run: docker push ghcr.io/aslisarikaya/note-app-docker-webapp:latest

    - name: Build DB Image
      run: docker build -t ghcr.io/aslisarikaya/note-app-docker-db:latest -f Dockerfile-db .

    - name: Push DB Image
      run: docker push ghcr.io/aslisarikaya/note-app-docker-db:latest
